### ISSUE TITLE
EU Mozillians Email

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/part-MakerParty#14]
Target Audience: All vouched Mozillians in the EU. 

CTA: Throw a Maker Party!
1. Host a planning meeting
2. Throw your maker party
3. Have a debrief 

Put it all on Nation Builder. 

Include info about getting budget through a Rep. 

Talk to Paul about marketing emails?

**Comment by LucyeoH-zz** [comment]
https://docs.google.com/document/d/1mwolk88AZK_YCC-cKFyj6TplqVk94MPFQJj3HoXzJrk/edit

**Comment by brianking** [comment]
@LucyeoH to write first draft

**Comment by brianking** [comment]
Closing .... reopen if anything is outstanding.
