### ISSUE TITLE
Write weekly emails

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/part-MakerParty#17]
https://docs.google.com/spreadsheets/d/1GWc5r4ughhsnlw_YVuZeo-CPMl9m2xaXUVCkPYeLEEA/edit#gid=2061737306

**Comment by brianking** [comment]
Blocked by #21

**Comment by brianking** [comment]
First email went out to push for logging events on the site.

Email to go out this week being tracked at:
https://docs.google.com/document/d/1mwolk88AZK_YCC-cKFyj6TplqVk94MPFQJj3HoXzJrk/edit#heading=h.uqh1n0jucs8x

**Comment by brianking** [comment]
Let's hack on this week's email here:

https://docs.google.com/document/d/1mwolk88AZK_YCC-cKFyj6TplqVk94MPFQJj3HoXzJrk/edit#heading=h.5zo3m7t4y0ww
