### ISSUE TITLE
Create Google Group for Mobilizers

### ISSUE THREAD

**Issue by brianking** [mozilla/part-MakerParty#21]
Once we have talked to people and they have committed, we should add them to a G Group for a regular cadence of communication.

**Comment by ghost** [comment]
I agree with this so will it be created for each makerparty or a common group will be also there?

**Comment by brianking** [comment]
The idea for this one is that it will be for one-way communications, to send out news and updates for mobilizers in the EU.

**Comment by brianking** [comment]
List created (invite only):

https://groups.google.com/a/mozilla.com/forum/?hl=en-GB#!forum/makerparty16-hosts
