### ISSUE TITLE
Global Email to Reps - Oct 12th

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/part-MakerParty#24]

**Comment by couci** [comment]
Hey @LucyoH what is the content that is going to be shared here?

**Comment by LucyeoH-zz** [comment]
Content [here](https://docs.google.com/document/d/1mwolk88AZK_YCC-cKFyj6TplqVk94MPFQJj3HoXzJrk/edit#) (locked)

**Comment by brianking** [comment]
Closing .... reopen if anything is outstanding.
