### ISSUE TITLE
Update General MP Wiki Page

### ISSUE THREAD

**Issue by brianking** [mozilla/part-MakerParty#25]
I will work with Colin Carruthers to update this page:

https://wiki.mozilla.org/Maker_Party

I think we can keep it simple and just add a blurb about copyright reform and link to the petition and the website. If there is archived materials from previous years, we can link to them from a separate section.

**Comment by LucyeoH-zz** [comment]
https://wiki.mozilla.org/Maker_Party

**Comment by brianking** [comment]
This seems done. Closing ... reopen if anything is outstanding.
