### ISSUE TITLE
Share Consultation opportunities with indiv EU Countries 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/part-MakerParty#28]
From Raegan:

---

We discussed possible actions for us around these consultations, and due to the tight timeline for many of them, combined with the outreach we're already doing on MP, we've opted for a light lift around this and to just inform our communities that this is going on to give them the option to participate and/or share with their networks.

Here's the information I have so far:
- Poland: [Consultation](http://www.prawoautorskie.gov.pl/pages/posts/resort-kultury-rozpoczal-konsultacje-dot.-propozycji-modernizacji-prawa-autorskiego-przedstawionych-przez-ke-949.php) – deadline: 14 October
- Sweden: more information missing – deadline: 21 October
- Germany (attached) - deadline 28 October
- Denmark - deadline 7 October
- Finland - deadline 15 October
- Austria - deadline 25 October

I am having trouble finding the links to the surveys, but hoping that our friends in C4C share them soon.

The idea would be to send a short email to these communities informing them that this is underway, and to encourage them to submit and/or share with others. We can encourage them to use or remix our petition, which makes it much easier for them to participate.

Let me know what you think - and in the case you have more luck finding these surveys, please be my guest :)

---

**Comment by brianking** [comment]
So there are 2 asks here:
1. Help in tracking down where the consultations are in some countries
2. Contribute to the consultation - give feedback

Community lists:
https://www.mozilla.org/en-US/about/forums/#regional

**Comment by brianking** [comment]
Last week I sent out to:
- Germany
- Sweden
- Ireland
- Poland

No followups except for Sweden where we got help in finding more information about the consultation.

Doing some individual followup for Austria. Waiting on more information about UK which Raegan says is coming soon.

**Comment by brianking** [comment]
UK consultation [shared with UK community last week](https://groups.google.com/forum/#!topic/mozilla.community.uk/85W9FXWU1xA).
