### ISSUE TITLE
Assign an outreach person for each Mobilizer

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/part-MakerParty#3]
TODO:
- [x] Assign outreach people - split group between Brian / Lucy
- [x] Draft followup email to those who signed up with main goal of setting up 1-1 time
- [ ] Have meetings and log notes
- [ ] Log event commitment numbers

**Comment by brianking** [comment]
Email sent to initial 24 people who signed up to find out more. I'm already seeing appointment requests coming in.

**Comment by brianking** [comment]
Tracking 1-1s and commitments here:
https://docs.google.com/a/mozilla.com/spreadsheets/d/1D5n0VXQwrMpB2aqCqGtkw1U7eUq_lwhrG_ZFSlz2524/edit?usp=sharing
