### ISSUE TITLE
Follow-up with New Mobilizers 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/part-MakerParty#30]
Arrange meetings with the [new mobilizers](https://docs.google.com/a/mozilla.com/forms/d/1uozgErI8wtT2HzIxpa3EAdSQ6hJHEfkgeI8jUmZMwVw/edit?c=0&w=1#responses) to get them to [commit](https://docs.google.com/spreadsheets/d/1D5n0VXQwrMpB2aqCqGtkw1U7eUq_lwhrG_ZFSlz2524/edit#gid=620371245) to mobilizing and running events in their region.

**Comment by brianking** [comment]
I'm seeing 10 new signups and 5 are from the EU.
