### ISSUE TITLE
Write Copy for EU Outreach Email

### ISSUE THREAD

**Issue by brianking** [mozilla/part-MakerParty#5]
We need some generic text we can use as a base for our initial outreach to initial EU mobilizers.

**Comment by LucyeoH-zz** [comment]
@brianking can you connect with Lainie on this? She's writing something similar that would be helpful and avoid duplication.

**Comment by brianking** [comment]
Almost final version waiting for review:

https://docs.google.com/a/mozilla.com/document/d/1mwolk88AZK_YCC-cKFyj6TplqVk94MPFQJj3HoXzJrk/edit?usp=sharing

**Comment by brianking** [comment]
Email sent out yesterday to EU based non-staff Reps.
