### ISSUE TITLE
Create Script for Webinars 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/part-MakerParty#8]

**Comment by brianking** [comment]
@LucyeoH Lainie mentioned on the call yesterday that these are changing content or getting an overhaul. Do you have more details?

**Comment by brianking** [comment]
Pulled out to separate doc here:
https://docs.google.com/document/d/1jj1_9Hta_X-XXBflFDqDOEhUill4rnMtUQiz3hV7lxU/edit

**Comment by brianking** [comment]
First draft written, sent to 270 for review. Meeting scheduled to go over, and rehearsal session setup for 27th. Live Webinar scheduled for 29th.
